### ISSUE TITLE
use `python3.8` and not `python3.9`

### ISSUE THREAD

**Issue by thsmit** [wilko339/MetaStruct#2]
Hi Toby, 

I installed MetaStruct and did run some examples. Cool stuff.

In my case I needed to use specifically `python3.8` and not `python3.9`. I don't know if this is general, but maybe you want to add it to the README.

**Comment by burhop** [comment]
Hi Toby,
I didn't have Ananconda so I had to install that first (this one in particular https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Windows-x86_64.exe ) . 

- The script then had a problem with building the mayavi wheel (see log)
- "conda install igl"  - Gave an error.  I changed to "conda install -c conda-forge igl" which worked.  I've attached a log of the session below (note:  WIndows 11 running on Anaconda Popwershell)

after that I ran the sphere_example() with no problem
[installLog.txt](https://github.com/wilko339/MetaStruct/files/7919402/installLog.txt)
.

**Comment by burhop** [comment]
> In my case I needed to use specifically `python3.8` and not `python3.9`. I don't know if this is general, but maybe you want to add it to the README.

Just curious what problem you saw with python3.9.  I read this after I had already gotten setup with python3.9.  It seems to be working but I haven't gotten that far yet.

**Comment by wilko339** [comment]
I'll take a look into this and try it out with 3.9. Yes curious to see what the issue was/is as well

**Comment by thsmit** [comment]
It looked like the same error as @burhop had. I tried installing using `python3.9` and then got: `ERROR: Failed building wheel for mayavi`. Then I switched to a new virtual environment with `python3.8` and try to install again which solved the problem.

**Comment by wilko339** [comment]
I've installed using python 3.9 and I also get the same error message during the mayavi installation. I get another error before from Mayavi stating that Numpy is required before mayavi, yet Numpy is installed before mayavi so I am not sure on the cause of this. It doesnt seem to prevent mayavi installing and working though.
