### ISSUE TITLE
`shell` function

### ISSUE THREAD

**Issue by thsmit** [wilko339/MetaStruct#4]
Hi Toby,

Is there something like a `shell` function available so that, for example, for the bracket, you can have a solid 'shell' with lattice infill. Any thoughts on this?

**Comment by wilko339** [comment]
Hi Thijs, yeah this would be a super useful function to have and I probably should have already done this! For now I will probably just add a uniform shell function, but it would be great to have a variable shell based on another field in the future!

**Comment by thsmit** [comment]
I will have a look if I can help :)
